services:
  database:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'babysitter'
      MYSQL_USER: 'joao.korczovei'
      MYSQL_PASSWORD: 'fGGZ7uQtK7ECm!l'
      MYSQL_ROOT_PASSWORD: 'fGGZ7uQtK7ECm!l'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - './.mysql-data/db:/var/lib/mysql'